### ISSUE TITLE
Missing `ForAll` and `Exists`

### ISSUE THREAD

**Issue by dpsanders** [ahumenberger/Z3.jl#17]
I need to use quantified statements that include `ForAll` and `Exists`, but these seem to be missing currently, as far as I can see?

**Comment by ahumenberger** [comment]
These need to be added to https://github.com/Z3Prover/z3/blob/master/src/api/julia/z3jl.cpp, which lists types, methods, etc. from the Z3 C++ API which should be exposed in Julia. Apparently formal and exists are still missing there. So what needs to be done is to look at the [Z3 C++ API](https://z3prover.github.io/api/html/namespacez3.html), and add the missing entries to https://github.com/Z3Prover/z3/blob/master/src/api/julia/z3jl.cpp.

Unfortunately, my time is too limited right now to do it myself. PRs are very welcome, and I'll try to help as much as possible!
Sorry for not responding earlier!

**Comment by dpsanders** [comment]
OK thanks, I'll try to do that!

**Comment by mlhetland** [comment]
Any progress on this? Would be great functionality to have in place :-)

**Comment by remysucre** [comment]
I exposed `exists` from the Z3 side and it will be available in the next Z3 release. You can also compile Z3 yourself to use it now, following the instructions [here](https://github.com/Z3Prover/z3/tree/master/src/api/julia).

**Comment by remysucre** [comment]
Now you can use `exists(ExprVector(ctx, [x, y, z]), e)`.
