### ISSUE TITLE
How to use pble

### ISSUE THREAD

**Issue by MFaisalZaki** [ahumenberger/Z3.jl#25]
I'm trying to assign weights to Boolean variables through `z3.if(var, 1.0, 0.0)` or using `z3.PbLe([(var,1)], 1)`, but there is no clear way on how to invoke this in Julia; it works fine with the python wrapper. Any help?

**Comment by remysucre** [comment]
`pble(ExprVector(ctx, [y]), [Int32(1)], 1)`

In general you can refer to the [C++ API doc](https://z3prover.github.io/api/html/namespacez3.html#a14164fb0ee5a409a64935aaf57e92336) since Z3.jl just wraps around that.
