### ISSUE TITLE
Missing Z3 API

### ISSUE THREAD

**Issue by MFaisalZaki** [ahumenberger/Z3.jl#29]
Like Z3py, we can define boolean and real variables using `z3.Bool('Variable_Name')`/`z3.Real('Variable_Name')`. However, there is no equivalent in z3.jl

**Comment by remysucre** [comment]
[Added](https://github.com/ahumenberger/Z3.jl/commit/7b522439b1d53475c8b5304301e0a80c4a4bd389) `BoolVar`. We're currently revamping the package to use the Z3 C API instead of the C++ API for stability, so many functions may be missing. You can try using a 0.* version for the old C++ API.
