### ISSUE TITLE
Use a JLL instead of building from scratch

### ISSUE THREAD

**Issue by shashi** [ahumenberger/Z3.jl#3]
I saw this being said on the z3 github issues, but opening an issue here for you.

I'm a noob at this, but can try to help. Would love to Pkg.add this package in seconds.

I noticed https://github.com/JuliaBinaryWrappers/z3_jll.jl, I might give this a try if you're not already working on that!

**Comment by ahumenberger** [comment]
Thank you, but I already have a [branch](https://github.com/ahumenberger/Z3.jl/tree/jll) where basically everything is set up. I'm just waiting for a new release of Z3 which includes the [Julia bindings](https://github.com/Z3Prover/z3/blob/master/src/api/julia/z3jl.cpp). Then z3_jll has to be updated and integrated into this package which shouldn't be a big effort.

**Comment by shashi** [comment]
Fantastic!!
