### ISSUE TITLE
pop takes a 2nd arg but push does not

### ISSUE THREAD

**Issue by shashi** [ahumenberger/Z3.jl#4]
but according to the spec they both do... Actually I'm not really sure what this number is supposed to be, but I'm suspecting it could be the cause of some crashes I'm seeing.

**Comment by ahumenberger** [comment]
I'm assuming you are talking about pop(::Solver, ::Int) and push(::Solver). These correspond to those from here: https://z3prover.github.io/api/html/classz3_1_1solver.html

push creates a backtracking point, and pop backtracks a certain amount of backtracking points.

**Comment by shashi** [comment]
Nice! Thank you again!
