### ISSUE TITLE
ASSERTION VIOLATION

### ISSUE THREAD

**Issue by Nosferican** [ahumenberger/Z3.jl#9]
Could there be a reason for https://github.com/Z3Prover/z3/issues/4728?
Could we investigate something on the Julia side?

**Comment by ahumenberger** [comment]
Sorry for the delay. I was pretty busy the last few weeks. The issue Z3Prover/z3#4728 is closed, is this still relevant?

**Comment by Nosferican** [comment]
The issue was closed based on some assumptions that aren't warranted given the context. I can test it again this week and let you know.

**Comment by remysucre** [comment]
Closing as stale
